version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nab5m^^
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  gnuboard:
    depends_on:
      - db
    image: skiychan/nginx-php7
    ports:
      - "8000:80"
    volumes:
      - .:/data/wwwroot
      - ./site.conf/default:/etc/nginx/sites-endabled/default
    command: sudo apt install -y php-gd
