version: '3'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=PassW@rd!!
      - MYSQL_USER=nab5m
      - MYSQL_PASSWORD=nab5m!_!
      - MYSQL_DATABASE=nab5m

  gnuboard:
    depends_on:
      - db
    image: skiychan/nginx-php7
    ports:
      - "8000:80"
    volumes:
      - .:/data/wwwroot
      - ./site.conf/default:/etc/nginx/sites-endabled/default
    command: sudo apt install -y php-gd
